### ISSUE TITLE
There is no VS 2015 version yet ;-)

### ISSUE THREAD

**Issue by PeterVdBoogaard** [kavengagne/ClipboardHistory#3]
Hi Kaven,

I really like this extension, and the fact that it isn't available for VS2015 makes me very sad.

regards
  Peter

**Comment by kavengagne** [comment]
Working on it right now!

**Comment by kavengagne** [comment]
Ho! Forgot to mention but it works on 2015 now! :) Enjoy.

**Comment by PeterVdBoogaard** [comment]
Thanks !! :-)
